# -*- coding: utf-8 -*-
"""AerofitCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5AuB0v1hYJMsjXKUxHo74kbkGmOZmsn

Aerofit is a leading brand in the field of fitness equipment. Aerofit provides a product range including machines such as treadmills, exercise bikes, gym equipment, and fitness accessories to cater to the needs of all categories of people.


# **Business Problem**

The market research team at AeroFit wants to identify the characteristics of the target audience for each type of treadmill offered by the company, to provide a better recommendation of the treadmills to the new customers. The team decides to investigate whether there are differences across the product with respect to customer characteristics.

Perform descriptive analytics to create a customer profile for each AeroFit treadmill product by developing appropriate tables and charts.
For each AeroFit treadmill product, construct two-way contingency tables and compute all conditional and marginal probabilities along with their insights/impact on the business.

**Product Portfolio:**

The KP281 is an entry-level treadmill that sells for $1,500.

The KP481 is for mid-level runners that sell for $1,750.

The KP781 treadmill is having advanced features that sell for $2,500.

# **Step‑by‑Step**

**1. Import Dataset & Explore Structure**
- Load the dataset
- Use commands like .head(), .info(), .describe() to understand columns, data types, and ranges.
- Verify the number of rows (180) and features (Product, Age, Gender, Education, MaritalStatus, Usage, Income, Fitness, Miles).

**2. Check Missing Values & Outliers**
- Use .isnull().sum() to confirm missing values.
- Plot boxplots for numerical variables (Age, Income, Miles, Usage) to detect outliers.
- Decide whether to keep, cap, or remove outliers depending on business relevance.

**3. Univariate Analysis (Each Column Separately)**
- Categorical variables: Frequency tables and bar charts (Product Purchased, Gender, MaritalStatus).
- Numerical variables: Histograms, mean/median, standard deviation (Age, Income, Usage, Miles, Fitness).
- Summarize typical customer profile (e.g., average age = 29, average income = $53K).

**4. Bivariate Analysis (Product vs. Other Features)**
- Create cross‑tabs (contingency tables) for Product vs. Gender, Product vs. Age group, Product vs. Income bracket.
- Use stacked bar charts or grouped plots to visualize differences.
- Example: KP281 buyers skew younger and lower income; KP781 buyers skew older and higher income.

**5. Calculate Marginal & Conditional Probabilities**
- Marginal probability: Overall probability of buying each product (e.g., P(KP281) = 44%).
- Conditional probability: Probability of buying a product given a characteristic (e.g., P(KP781  Male) vs. P(KP781  Female)).
- Present results in tables with percentages to highlight differences.

**6. Build Customer Profiles for Each Treadmill**

- Summarize each profile with age, income, fitness level, and usage patterns.

**7. Final Recommendations**

# **STEP 1: Importing Dataset & understanding its structure**
"""

# Step 1: Import libraries and dataset
import pandas as pd

# Load the dataset
df = pd.read_csv("aerofit_treadmill.csv")

# Check first 5 rows
print("Preview of dataset:")
print(df.head())

# Shape of dataset
print("\nShape of dataset (rows, columns):", df.shape)

# Info about datatypes
print("\nDataset Info:")
print(df.info())

# Summary statistics
print("\nStatistical Summary:")
print(df.describe(include='all'))

"""The dataset has 180 customers in total and 9 features i.e., age, gender, income, fitness, treadmill purchased.

There are no missing values.

The average customer age is 29 years old with an income of ~$53K.

They use the treadmill about 3–4 times per week.

# **STEP 2: Outlier Detection**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Outlier Detection

# 1. Check statistical summary
print("Summary statistics:")
print(df.describe())

# 2. Boxplots for numeric columns
num_cols = ["Age", "Education", "Usage", "Fitness", "Income", "Miles"]

plt.figure(figsize=(15,8))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(y=df[col])
    plt.title(f"Boxplot of {col}")
plt.tight_layout()
plt.show()

"""The features are usually in normal range, except 'Income' and 'Miles' showing some very high earners and heavy users.

Few outliers can be spotted in 'Age', 'Education' and 'Usage' which are reasonable and do not look like data errors since they do not deviate by a lot.

Since the outliers likely represent real customers i.e., athletes or wealthy buyers, they will be considered in the data.

# **STEP 3: Univariate Analysis**

For Categorical Variables - 'Product', 'Gender', 'MaritalStatus':
Countplot/PieChart is used

For Mumerical Analysis - 'Age', 'Education', 'Usage', 'Fitness', 'Income', 'Miles':
Hisplot/Displot is used
"""

# Step 3: Univariate Analysis
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Product Purchased
plt.figure(figsize=(6,4))
sns.countplot(x='Product', data=df)
plt.title("Distribution of Products Purchased")
plt.show()

# 2. Gender
plt.figure(figsize=(6,4))
sns.countplot(x='Gender', data=df)
plt.title("Distribution of Gender")
plt.show()

# 3. Marital Status
plt.figure(figsize=(6,4))
sns.countplot(x='MaritalStatus', data=df)
plt.title("Distribution of Marital Status")
plt.show()

# 4. Age Distribution
plt.figure(figsize=(6,4))
sns.histplot(df['Age'], bins=15, kde=True)
plt.title("Age Distribution")
plt.show()

# 5. Income Distribution
plt.figure(figsize=(6,4))
sns.histplot(df['Income'], bins=20, kde=True)
plt.title("Income Distribution")
plt.show()

# 6. Miles Distribution
plt.figure(figsize=(6,4))
sns.histplot(df['Miles'], bins=20, kde=True)
plt.title("Distribution of Miles")
plt.show()

"""Distribution of Products Purchased: Most customers purchased KP281 (entry-level), followed by KP481 and KP781.

Distribution of Gender: Majority are Male customers, though females also form a good share.

Distribution of Marital Status: More customers are Partnered than Single.

Age Distribution: Customers are mostly 20–35 years old, with a peak around mid-20s.

Income Distribution: Income is mostly between
60K, but a few high-income customers exist.

Distribution of Miles: Most customers expect to run 50–120 miles per week, though some extreme fitness users go much higher.

# **Bivariate Analysis**

For categorical features - 'Product' vs 'Gender', 'Marital Status': Countplots are used

For numeric features - 'Product vs Age', 'Income', 'Usage', 'Fitness', 'Miles': Boxplots/Violin plots are used
"""

# 1. Product vs Gender
plt.figure(figsize=(6,4))
sns.countplot(x="Product", hue="Gender", data=df)
plt.title("Product vs Gender")
plt.show()

# 2. Product vs Marital Status
plt.figure(figsize=(6,4))
sns.countplot(x="Product", hue="MaritalStatus", data=df)
plt.title("Product vs Marital Status")
plt.show()

# 3. Product vs Age
plt.figure(figsize=(6,4))
sns.boxplot(x="Product", y="Age", data=df)
plt.title("Product vs Age")
plt.show()

# 4. Product vs Income
plt.figure(figsize=(6,4))
sns.boxplot(x="Product", y="Income", data=df)
plt.title("Product vs Income")
plt.show()

# 5. Product vs Fitness
plt.figure(figsize=(6,4))
sns.boxplot(x="Product", y="Fitness", data=df)
plt.title("Product vs Fitness")
plt.show()

# 6. Product vs Miles
plt.figure(figsize=(6,4))
sns.boxplot(x="Product", y="Miles", data=df)
plt.title("Product vs Miles")
plt.show()

"""**Product vs Gender:**

Both males and females buy all products, but entry-level KP281 is commonly bought by males.


**Product vs Marital Status:**

Partnered people tend to buy mid and high-end models more in comparison to singles.


**Product vs Age:**

Younger customers aged 20–30 years mostly buy KP281, while older customers aged 30–40 years go for KP781.


**Product vs Income:**

Higher income customers prefer KP781, while lower income customers go for KP281.


**Product vs Fitness:**

KP781 buyers have higher fitness ratings '4'–'5', while KP281/KP481 buyers usually rate '2'–'3'.


**Product vs Miles:**

More miles per week are covered by KP781 buyers, indicating them to be serious runners, while KP281 buyers expect fewer miles.

# **STEP 4: Marginal & Conditional Probability**

Marginal Probability- % of customers that purchased KP281, KP481, or KP781

Conditional Probability- The probability of a male customer buying KP781
"""

# Step 4: Marginal & Conditional Probabilities

import pandas as pd

# Marginal Probability - Product Distribution
product_counts = df['Product'].value_counts(normalize=True) * 100
print("Marginal Probability (Product Distribution %):")
print(product_counts)

# Two-way contingency table: Product vs Gender
gender_table = pd.crosstab(df['Gender'], df['Product'], margins=True)
print("\nContingency Table: Product vs Gender")
print(gender_table)

# Conditional probability: P(Product | Gender)
cond_prob_gender = pd.crosstab(df['Gender'], df['Product'], normalize='index') * 100
print("\nConditional Probability of Product given Gender:")
print(cond_prob_gender)

# Two-way contingency table: Product vs Marital Status
marital_table = pd.crosstab(df['MaritalStatus'], df['Product'], margins=True)
print("\nContingency Table: Product vs Marital Status")
print(marital_table)

# Conditional probability: P(Product | Marital Status)
cond_prob_marital = pd.crosstab(df['MaritalStatus'], df['Product'], normalize='index') * 100
print("\nConditional Probability of Product given Marital Status:")
print(cond_prob_marital)

"""Around 44% customers bought KP281, 33% bought KP481, and 22% bought KP781.

According to Gender → Females mostly buy KP281 (53%), while males are more balanced, with 32% of them choosing the advanced KP781.

According to Marital Status → Partnered and single customers show similar patterns, but singles have a slightly higher preference for KP781.

# **STEP 5: Correlation Analysis**
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Select only numeric columns
num_df = df.select_dtypes(include=['int64', 'float64'])

# Correlation matrix
corr_matrix = num_df.corr()

# Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Pairplot (optional detailed view)
sns.pairplot(num_df)
plt.show()

"""- Age and Income are directly proportional: older customers tend to earn more.

- Fitness, Usage, and Miles are again directly proportional → fit customers run more miles and use treadmills more often.

- Education shows little to no correlation with other features.

# **STEP 7: Customer Profiling**

Males are 3 times more likely than females to buy the high-end KP781

Females mostly prefer the entry-level KP281
"""

# Conditional probability: P(Product | Gender)
cond_prob_gender = pd.crosstab(df['Gender'], df['Product'], normalize='index') * 100
print(cond_prob_gender)

"""- **KP281 (Entry-level, $1500)**

Age: Mostly 18–28 years

Income: Lower (~30k-45K)

Fitness: 2–3 (average fitness)

Usage: 2–3 times per week, fewer miles

Demographics: More males and singles Profile: Young beginners, casual users, budget-conscious buyers.

- **KP481 (Mid-level, $1750)**

Age: 25–35 years

Income: Medium (~45k-60K)

Fitness: 3–4 (regular exercisers)

Usage: 3–4 times per week, moderate miles

Demographics: Balanced mix of males & females, many partnered Profile: Regular fitness users who want balance of features & price.

- **KP781 (Advanced, $2500)**

Age: 30–40 years

Income: High (~$60K+)

Fitness: 4–5 (fit/athletic customers)

Usage: 5–7 times per week, high miles

Demographics: Mostly males, more partnered Profile: Serious fitness enthusiasts, athletes, or high-income professionals.

# **STEP 8: Probability-  Marginal & Conditional Summary**
"""

# Marginal probability (product %)
product_dist = df['Product'].value_counts(normalize=True) * 100
print(product_dist)

# Conditional by Gender
cond_by_gender = pd.crosstab(df['Gender'], df['Product'], normalize='index') * 100
print(cond_by_gender.round(2))

# Conditional by Marital Status
cond_by_marital = pd.crosstab(df['MaritalStatus'], df['Product'], normalize='index') * 100
print(cond_by_marital.round(2))

"""- Entry-level KP281 (44%) is bought by most customers

- KP781 is the least common (22%).

- Males are much more likely to choose KP781 (32%)

- Females mostly prefer KP281 (53%).

- Marital status has little effect — partnered and single customers show almost the same product mix.

# **STEP 9: Actionable Insights & Recommendations**

**KP281 – Entry-Level ($1,500)**
- Target Audience: Primarily younger customers (18–28 years), lower income groups, and beginners in fitness.
- Strategic Actions: Position KP281 as the affordable starter option. Use student discounts, online advertising, and budget-friendly bundles to attract this segment.
- Growth Path: Introduce loyalty programs or trade-in schemes that encourage customers to upgrade to mid- or advanced models (KP481/KP781) as their fitness needs evolve.

**KP481 – Mid-Level ($1,750)**
- Target Audience: Working professionals aged 25–35, with medium income levels and a fitness-conscious lifestyle.
- Strategic Actions: Market KP481 as the “best value” treadmill, emphasizing durability and suitability for family use.
- Promotion Tactics: Bundle with complementary fitness accessories (e.g., mats, dumbbells) to enhance appeal and increase average purchase value.

**KP781 – Advanced ($2,500)**

- Target Audience: High-income customers (>$60K), typically aged 30–40, with strong fitness commitment (self-rated 4–5).
- Strategic Actions: Position KP781 as a premium product. Promote through partnerships with gyms, health clubs, and corporate wellness programs.
- Branding Focus: Highlight advanced features, long-term durability, and superior performance to reinforce its premium status.

**Gender-Based Strategy**
- Male Customers: Males are three times more likely to purchase KP781. Focus premium treadmill advertising and campaigns toward male audiences.
- Female Customers: Females show stronger preference for KP281. Offer affordable starter packages and bundle fitness apps to encourage adoption.

**General Recommendations**
- Implement personalized recommendations based on customer demographics (age, income, fitness score).
- Launch email campaigns that suggest the most suitable treadmill model after collecting survey inputs from new customers.
- Drive cross-selling opportunities by offering accessories (shoes, mats, wearables) to increase customer lifetime value.

# **Case Study Summary**

Aerofit offers three treadmill models: KP281 (Entry, $1,500), KP481 (Mid, $1,750), and KP781 (Advanced, $2,500). The company’s goal was to understand customer profiles for each product to improve targeting and recommendations.

**Key Findings**

- Dataset Overview: 180 customers, no missing values. Average age: 29 years; average income: $53K; average weekly mileage: ~100 miles.

- Product Distribution: KP281 accounted for 44% of sales, KP481 for 33%, and KP781 for 22%.

- Customer Segments:
  - KP281: Younger buyers (18–28), lower income, fitness beginners, casual users.
  - KP481: Adults (25–35), medium income, balanced gender mix, regular fitness users.
  - KP781: Older customers (30–40), higher income (> $60K), advanced fitness levels, predominantly male.
- Gender Effect: Females lean toward KP281 (53%), while males are three times more likely to purchase KP781 (32%).
- Behavioral Patterns: Age and income rise together; fitness, usage, and mileage are strongly correlated.

**Business Recommendations**
- KP281: Market to young, budget-conscious customers (students, early professionals). Position as the ideal starter treadmill with affordable bundles.
- KP481: Promote as the “best value” option for working adults and families. Enhance appeal through accessory bundles (mats, dumbbells).
- KP781: Target high-income, serious fitness users. Advertise in premium gyms, wellness clubs, and corporate wellness programs.
- Gender Strategy: Focus KP781 promotions on male audiences; design KP281 starter packs with female buyers in mind.
- Upgrade Path: Introduce trade-in and loyalty programs to transition customers from KP281 → KP481 → KP781 over time.
- Personalization: Use age, income, and fitness scores to deliver tailored recommendations. Support with email campaigns and cross-sell accessories (shoes, mats, wearables) to increase lifetime value.

**In Short**
- Most customers prefer the entry-level KP281.
- Men are more likely to invest in the premium KP781.
- Age, income, and fitness level are strong predictors of product choice.
- Aerofit can grow sales by aligning each treadmill with the right customer segment and offering structured upgrade opportunities.
"""